### ISSUE TITLE
Create code for the arm

### ISSUE THREAD

**Issue by TheComputer314** [icrobotics-team167/2024_Crescendo#6]

**Comment by TheComputer314** [comment]
Created Pivot.java and updated motor classes to add configureInverted and configureFollow, and to fix a typo (configurePIDs was named configrePIDs)

**Comment by cotc167** [comment]
Created Extension.java, Claw.java, ArmSubsystem.java, and RevNEO550.java. Got started on implementing ArmSubsystem, and the Commands are to be implemented.

**Comment by cotc167** [comment]
Created the command to move the arm, in commit 6d11084

**Comment by TheComputer314** [comment]
e4be3a6375bd6842f24e5f97c1dd0d846ce2d1bc, Done
